name: Download and Commit File

on:
  push:
    branches:
      - main

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download file
      run: curl -L -o downloaded_file.txt https://example.com/file.txt

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add downloaded_file.txt
        git commit -m "Add downloaded file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
