name: Download File Workflow

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: 'URL of the file to download'
        required: true
        default: 'https://example.com/file.zip'

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download file
      run: |
        echo "Downloading file from URL: ${{ github.event.inputs.download_url }}"
        curl -L -o downloaded_file ${{ github.event.inputs.download_url }}

    - name: Configure Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Commit file to repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add downloaded_file
        git commit -m "Add downloaded file"
        git push
