name: Download File Workflow

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: 'URL of the file to download'
        required: true
        default: 'https://example.com/file.zip'

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download file
      run: |
        echo "Downloading file from URL: ${{ github.event.inputs.download_url }}"
        curl -L -o downloaded_file ${{ github.event.inputs.download_url }}

    - name: List downloaded file
      run: ls -l downloaded_file
