name: Run Pake and Package for Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install pip dependencies (if any)
      run: |
        python -m pip install --upgrade pip

    - name: Run Python script to setup and execute Pake
      run: python run_pake.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: pake-output
        path: ./
