name: GitHub测试

on:
  workflow_dispatch:
    inputs:
      user_message:
        description: '输入您的留言'
        required: true
        default: 'GitHub测试！'
  schedule:
    - cron: "*/2 * * * *"  # Schedule to run every 3 minutes

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub测试
        run: |
          current_time=$(date "+%Y-%m-%d %H:%M:%S")
          user_message="${{ github.event.inputs.user_message }}"
          curl -d "text=$user_message 当前时间：$current_time" http://miaotixing.com/trigger?id=tzLyHCO
