name: Upload to WebDAV

on:
  push:
    branches:
      - main  # 根据你的主分支修改

jobs:
  upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Download file with yt-dlp
        run: |
          yt-dlp https://www.youtube.com/watch?v=dQw4w9WgXcQ -o "downloaded_file.mp4"  # 替换为你要下载的文件的 URL 和文件名
        
      - name: Upload to WebDAV
        run: |
          curl -T downloaded_file.mp4 -u "lele1894:yD9R7YJdXNMHZ5fm" https://higa.teracloud.jp/dav/
        # 替换账号和密码为你的 WebDAV 服务器的实际账号和密码，URL 也需要根据实际情况修改

