name: 上传到WebDAV

on:
  push:
    branches:
      - main  # 这里改成你的默认分支
  workflow_dispatch:
    inputs:
      download_url:
        description: '要下载的文件的 URL'
        required: false
        default: 'https://example.com/path/to/your/file.txt'

jobs:
  upload:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境，你也可以选择其他支持的操作系统

    steps:
      - name: 拉取代码
        uses: actions/checkout@v2  # 拉取最新的代码

      - name: 设置下载地址
        run: echo "DOWNLOAD_URL=${{ github.event.inputs.download_url || 'https://example.com/path/to/your/file.txt' }}" >> $GITHUB_ENV

      - name: 下载文件
        run: |
          curl -O $DOWNLOAD_URL  # 使用环境变量中的下载 URL

      - name: 上传到WebDAV
        uses: srt32/webdav-upload-action@v1
        with:
          endpoint: 'https://higa.teracloud.jp/dav/'  # WebDAV 服务器地址
          username: 'lele1894'  # 替换为你的账号
          password: 'yD9R7YJdXNMHZ5fm'  # 替换为你的密码
          localPath: $(basename $DOWNLOAD_URL)  # 获取文件名并作为本地文件路径
          remotePath: /  # 远程 WebDAV 目录路径，这里可以根据需要修改
