name: Docker Hello World Example

on: [push]

jobs:
  docker-hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Run Hello World container
      run: docker run --rm -it -p 1935:1935 -p 1985:1985 -p 8080:8080 \
        -p 8000:8000/udp -p 10080:10080/udp ossrs/srs:5
