name: Download and html

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'URL of the YouTube video to download'
        required: true
        default: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'

jobs:
  download_video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install yt-dlp
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp

    - name: Download video
      run: |
        timestamp=$(date +'%Y%m%d%H%M%S')
        yt-dlp -o "${timestamp}.%(ext)s" "${{ github.event.inputs.video_url }}"

    - name: Get downloaded file name
      id: get_filename
      run: |
        FILE=$(ls | grep -E '[0-9]{14}\.[a-z0-9]+')
        echo "filename=$FILE" >> $GITHUB_ENV

    - name: Generate HTML file
      run: |
        echo "<html><body><video width='640' height='360' controls><source src='${{ env.filename }}' type='video/mp4'></video></body></html>" > index.html

    - name: Deploy HTML file
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        commit_message: "Publish video playback page"

    - name: Display video playback URL
      run: |
        echo "Video playback URL: https://${{ github.repository_owner }}.github.io/${{ github.repository_name }}/index.html"
