name: Download and Upload Video to WebDAV

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'URL of the YouTube video to download'
        required: true
        default: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'

jobs:
  download_upload_video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install yt-dlp
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp

    - name: Download video
      run: |
        timestamp=$(date +'%Y%m%d%H%M%S')
        filename="${timestamp}.mp4"
        yt-dlp -o "${filename}" "${{ github.event.inputs.video_url }}"

    - name: Print downloaded file path
      run: |
        ls -l

    - name: Upload to WebDAV
      run: |
        rclone copy "${timestamp}.mp4" webdav:https://higa.teracloud.jp/dav/ \
          --webdav-user='lele1894' \
          --webdav-pass='yD9R7YJdXNMHZ5fm'

    - name: Display WebDAV upload status
      run: |
        echo "File uploaded to WebDAV: https://higa.teracloud.jp/dav/${timestamp}.mp4"
