name: 持续推送至 RTMP

on:
  workflow_dispatch:
    inputs:
      stop:
        description: 'Stop the continuous RTMP push'
        required: false
        default: 'false'
        type: boolean
      video_url:
        description: 'rtmp'
        required: true
        default: 'rtmp://168.138.93.68/live/livestream'
      yt_url:
        description: 'youtube地址'
        required: true
        default: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'
      yt_gz:
        description: 'yt分辨率选择'
        required: true
        default: "-f 'bestvideo[height<=720][vcodec!=vp9][width>=1280]+bestaudio/best' --merge-output-format mp4"


jobs:
  push-to-rtmp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ffmpeg
        run: |
          sudo apt-get install ffmpeg -y
          pip install yt-dlp

      - name: Push video to RTMP
        run: |
          while true; do
            yt-dlp "${{ github.event.inputs.yt_url }}" -o - | ffmpeg -re -i pipe:0 -c copy -f flv "${{ github.event.inputs.video_url }}"
            if [ ${{ github.event.inputs.stop }} == 'true' ]; then
            echo "Stopping continuous push as requested."
            exit 0
            fi
          done
