name: d1

on:
  workflow_dispatch:
  schedule:
    - cron: "1 * * * *"

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub测试
        run: |
          current_time=$(date "+%Y-%m-%d %H:%M:%S")
          curl -d "text=GitHub测试！当前时间：$current_time" http://miaotixing.com/trigger?id=tzLyHCO
