name: d1

on: workflow_dispatch  
  schedule:
    - cron: "20 * * * *"

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub测试
        run: |
          curl -d "text=GitHub测试！" http://miaotixing.com/trigger?id=tzLyHCO

