name: Download File Example

on: [push]

jobs:
  download-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download a file using wget
      run: wget -O downloaded_file https://lf3-package.vlabstatic.com/obj/faceu-packages/installer/jianying_jianyingpro_0_1.2.7_installer.exe

    - name: Print the full path of the downloaded file
      run: echo "$(pwd)"

    - name: List files in current directory
      run: ls -al
