name: 手动上传到 WebDAV

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: 'URL of the file to download'
        required: true
      webdav_endpoint:
        description: 'WebDAV server endpoint'
        required: true
      webdav_username:
        description: 'WebDAV username'
        required: true
      webdav_password:
        description: 'WebDAV password'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest

    env:
      DOWNLOAD_URL: ${{ github.event.inputs.download_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download file with curl
        run: |
          curl -L -o downloaded_file "${DOWNLOAD_URL}"

      - name: Upload file to WebDAV
        run: |
          curl -T downloaded_file -u ${{ github.event.inputs.webdav_username }}:${{ github.event.inputs.webdav_password }} "${{ github.event.inputs.webdav_endpoint }}/$(basename $DOWNLOAD_URL)"
