name: 持续推送至 RTMP

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'rtmp'
        required: true
        default: 'rtmp://168.138.93.68/live/livestream'
      yt_url:
        description: 'youtube地址'
        required: true
        default: '92IaqdAkYO0'
      yt_gz:
        description: 'yt分辨率选择'
        required: true
        default: "-f 95"


jobs:
  push-to-rtmp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ffmpeg
        run: |
          sudo apt-get install ffmpeg -y
          pip install yt-dlp

      - name: Push video to RTMP
        run: |
          yt-dlp "${{ github.event.inputs.yt_gz }}" "${{ github.event.inputs.yt_url }}" -o - | ffmpeg -re -i pipe:0 -c copy -f flv "${{ github.event.inputs.video_url }}"
