name: Build Pake on Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Microsoft Visual Studio C++ Build Tools
      run: |
        choco install visualstudio2019buildtools --version=16.11.0.0 --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --includeOptional" -y
        setx PATH "%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
        setx PATH "%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64"

    - name: Install rustup
      run: |
        curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
        setx PATH "%PATH%;C:\Users\runneradmin\.cargo\bin"

    - name: Install pake-cli
      run: npm install -g pake-cli

    - name: Run pake
      run: pake ./index.html --name html-test --use-local-file

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: pake-output
        path: ./
