name: 持续推送至 RTMP

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'rtmp'
        required: true
        default: 'rtmp://'
      webdav_endpoint:
        description: 'WebDAV 服务器端点'
        required: true
        default: 'https://higa.teracloud.jp/dav/'
      webdav_username:
        description: 'WebDAV 用户名'
        required: true
      webdav_password:
        description: 'WebDAV 密码'
        required: true

jobs:
  push-to-rtmp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ffmpeg
        run: sudo apt-get install ffmpeg -y

      - name: Push video to RTMP
        run: |
            ffmpeg -re -stream_loop -1 -i 20240619150133.mp4 -c copy -f flv "${{ github.event.inputs.video_url }}"
