name: Ngrok Expose

on:
  push:
    branches:
      - main  # 触发主分支的推送事件，可以根据需要调整

jobs:
  expose:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # 替换为你的 Python 版本，如果需要的话

    - name: Install Ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        sudo mv ngrok /usr/local/bin/ngrok
        ngrok version  # 验证安装是否成功

    - name: Start HTTP server
      run: |
        python -m http.server 8000 &  # 在后台启动简单的 HTTP 服务器，监听端口 8000

    - name: Expose server with Ngrok
      run: |
        ngrok http 8000  # 使用 Ngrok 将本地服务器的端口 8000 映射到公共网络

