name: cuel下载传到WebDAV

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: '要下载的文件的 URL'
        required: true
      webdav_endpoint:
        description: 'WebDAV 服务器端点'
        required: true
      webdav_username:
        description: 'WebDAV 用户名'
        required: true
      webdav_password:
        description: 'WebDAV 密码'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest

    env:
      DOWNLOAD_URL: ${{ github.event.inputs.download_url }}

    steps:
      - name: 拉取码
        uses: actions/checkout@main
        with:
          node-version: '20'  # or a higher supported version

      - name: 使用curl下载文件
        run: |
          curl -L -o downloaded_file "${DOWNLOAD_URL}"

      - name: 将文件上传到 WebDAV
        run: |
          curl -T downloaded_file -u ${{ github.event.inputs.webdav_username }}:${{ github.event.inputs.webdav_password }} "${{ github.event.inputs.webdav_endpoint }}/$(basename $DOWNLOAD_URL)"
