name: Download YouTube Video Workflow

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'URL of the YouTube video to download'
        required: true
        default: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'

jobs:
  download_video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 使用支持 Node.js 20 的版本

    - name: Set up Python
      uses: actions/setup-python@v4  # 使用支持 Node.js 20 的版本
      with:
        python-version: '3.x'

    - name: Install yt-dlp
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp

    - name: Download video
      run: |
        timestamp=$(date +'%Y%m%d%H%M%S')
        yt-dlp -o "${timestamp}.%(ext)s" "${{ github.event.inputs.video_url }}"

    - name: Get downloaded file name
      id: get-filename
      run: |
        FILE=$(ls | grep -E '[0-9]{14}\.[a-z0-9]+')
        echo "filename=$FILE" >> $GITHUB_ENV

    - name: Print downloaded file path
      run: echo "Downloaded file: ${{ env.filename }}"

    - name: Configure Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Add and commit video to repository
      run: |
        git add .
        git commit -m "Add downloaded video"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
