name: 下载 YouTube 视频

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: '要下载的 YouTube 视频的 URL'
        required: true
        default: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'

jobs:
  download_video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 使用支持 Node.js 20 的版本

    - name: 设置Python
      uses: actions/setup-python@v4  # 使用支持 Node.js 20 的版本
      with:
        python-version: '3.x'

    - name: 安装 yt-dlp
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp

    - name: 下载视频
      run: |
        timestamp=$(date +'%Y%m%d%H%M%S')
        yt-dlp -o "${timestamp}.%(ext)s" "${{ github.event.inputs.video_url }}"

    - name: 配置Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: 添加视频并将其提交到存储库
      run: |
        git add .
        git commit -m "Add downloaded video"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
