name: 下载并上传 YouTube 视频到 WebDAV

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: '要下载的 YouTube 视频的 URL'
        required: true
        default: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'
      webdav_endpoint:
        description: 'WebDAV 服务器端点'
        required: true
        default: 'https://higa.teracloud.jp/dav/'
      webdav_username:
        description: 'WebDAV 用户名'
        required: true
      webdav_password:
        description: 'WebDAV 密码'
        required: true

jobs:
  download_and_upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          node-version: '20'

      - name: Install yt-dlp
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: Get current time
        id: current_time
        run: echo "CURRENT_TIME=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV

      - name: Download video and get filename
        id: download
        run: |
          filename="${{ env.CURRENT_TIME }}.mp4"
          yt-dlp -o "${filename}" "${{ github.event.inputs.video_url }}"
          echo "::set-output name=filename::${filename}"  # Use set-output to pass filename to the next step

      - name: Upload to WebDAV
        env:
          WEBDAV_ENDPOINT: ${{ github.event.inputs.webdav_endpoint }}
          WEBDAV_USERNAME: ${{ github.event.inputs.webdav_username }}
          WEBDAV_PASSWORD: ${{ github.event.inputs.webdav_password }}
          DOWNLOAD_URL: ${{ steps.download.outputs.filename }}
        run: |
          curl -T "${DOWNLOAD_URL}" -u "${WEBDAV_USERNAME}:${WEBDAV_PASSWORD}" "${WEBDAV_ENDPOINT}/$(basename "${DOWNLOAD_URL}")"
