name: 下载YouTube视频到WEBDAV

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: '要下载的 YouTube 视频的 URL'
        required: true
        default: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'
      webdav_endpoint:
        description: 'WebDAV 服务器端点'
        required: true
        default: 'https://higa.teracloud.jp/dav/'
      webdav_username:
        description: 'WebDAV 用户名'
        required: true
      webdav_password:
        description: 'WebDAV 密码'
        required: true

jobs:
  download_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 设置 Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 安装 yt-dlp
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: 下载视频并获取文件名
        id: download
        run: |
          timestamp=$(date +'%Y%m%d%H%M%S')
          downloaded_file="${timestamp}.%(ext)s"
          yt-dlp -o "${downloaded_file}" "${{ github.event.inputs.video_url }}"
          echo "::set-output name=downloaded_file::${downloaded_file}"

      - name: 输出下载的文件名
        run: |
          echo "下载的文件名是: ${{ steps.download.outputs.downloaded_file }}"

      - name: 将文件上传到 WebDAV
        run: |
          curl -T "${{ steps.download.outputs.downloaded_file }}" -u ${{ github.event.inputs.webdav_username }}:${{ github.event.inputs.webdav_password }} "${{ github.event.inputs.webdav_endpoint }}/$(basename downloaded_file)"
