name: 下载并上传 YouTube 视频到 WebDAV

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: '要下载的 YouTube 视频的 URL'
        required: true
        default: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'
      webdav_endpoint:
        description: 'WebDAV 服务器端点'
        required: true
        default: 'https://higa.teracloud.jp/dav/'
      webdav_username:
        description: 'WebDAV 用户名'
        required: true
      webdav_password:
        description: 'WebDAV 密码'
        required: true

jobs:
  download_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 设置 Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 安装 yt-dlp
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: 下载视频并获取文件名
        id: download
        run: |
          filename=$(yt-dlp --get-filename "${{ github.event.inputs.video_url }}")
          echo "::set-output name=filename::${filename}"

      - name: 上传到 WebDAV
        env:
          WEBDAV_ENDPOINT: ${{ github.event.inputs.webdav_endpoint }}
          WEBDAV_USERNAME: ${{ github.event.inputs.webdav_username }}
          WEBDAV_PASSWORD: ${{ github.event.inputs.webdav_password }}
        run: |
          curl -T "${{ steps.download.outputs.filename }}" \
               -u "${WEBDAV_USERNAME}:${WEBDAV_PASSWORD}" \
               "${WEBDAV_ENDPOINT}/$(basename "${{ steps.download.outputs.filename }}")"
